const START_GETTING_FORECAST = 'START_GETTING_FORECAST';
const SUCCESS_GETTING_FORECAST = 'SUCCESS_GETTING_FORECAST';
const FAIL_GETTING_FORECAST = 'FAIL_GETTING_FORECAST';

export default {
  START_GETTING_FORECAST,
  SUCCESS_GETTING_FORECAST,
  FAIL_GETTING_FORECAST,
};
