const START_GETTING_LOCATION = 'START_GETTING_LOCATION';
const SUCCESS_GETTING_LOCATION = 'SUCCESS_GETTING_LOCATION';
const FAIL_GETTING_LOCATION = 'FAIL_GETTING_LOCATION';

export default {
  START_GETTING_LOCATION,
  SUCCESS_GETTING_LOCATION,
  FAIL_GETTING_LOCATION,
};
